spring.application.name=planet_project_manual
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.main.banner-mode=off
logging.level.root=error
logging.level.sql=info
spring.datasource.generate-unique-name=false
spring.mvc.pathmatch.matching-strategy=path_pattern_parser

spring.jpa.generate-ddl=true
spring.jackson.default-property-inclusion=non_null

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true

#spring.security.user.password=password
#spring.security.user.name=user